<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit59678e773c81f4023d7fcd4ab2492970 {

	public static $prefixLengthsPsr4 = array(
		'E' =>
		array(
			'EQUD\\' => 5,
		),
	);

	public static $prefixDirsPsr4 = array(
		'EQUD\\' =>
		array(
			0 => __DIR__ . '/..' . '/src',
		),
	);

	public static $classMap = array(
		'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
	);

	public static function getInitializer( ClassLoader $loader ) {
		return \Closure::bind(
			function () use ( $loader ) {
				$loader->prefixLengthsPsr4 = ComposerStaticInit59678e773c81f4023d7fcd4ab2492970::$prefixLengthsPsr4;
				$loader->prefixDirsPsr4    = ComposerStaticInit59678e773c81f4023d7fcd4ab2492970::$prefixDirsPsr4;
				$loader->classMap          = ComposerStaticInit59678e773c81f4023d7fcd4ab2492970::$classMap;

			},
			null,
			ClassLoader::class
		);
	}
}
