<?php

// autoload_real.php @generated by Composer
class ComposerAutoloaderInit59678e773c81f4023d7fcd4ab2492970 {

	private static $loader;


	public static function loadClassLoader( $class ) {
		if ( 'Composer\Autoload\ClassLoader' === $class ) {
			include __DIR__ . '/ClassLoader.php';
		}
	}//end loadClassLoader()


	/**
	 * @return \Composer\Autoload\ClassLoader
	 */
	public static function getLoader() {
		if ( null !== self::$loader ) {
			return self::$loader;
		}

		spl_autoload_register( array( 'ComposerAutoloaderInit59678e773c81f4023d7fcd4ab2492970', 'loadClassLoader' ), true, true );
		self::$loader = $loader = new \Composer\Autoload\ClassLoader( \dirname( __DIR__ ) );
		spl_autoload_unregister( array( 'ComposerAutoloaderInit59678e773c81f4023d7fcd4ab2492970', 'loadClassLoader' ) );

		include __DIR__ . '/autoload_static.php';
		call_user_func( \Composer\Autoload\ComposerStaticInit59678e773c81f4023d7fcd4ab2492970::getInitializer( $loader ) );

		$loader->register( true );

		return $loader;
	}//end getLoader()
}//end class
